### ISSUE TITLE
Prometheus e2e performance test as a replacement of prombench

### ISSUE THREAD

**Issue by krasi-georgiev** [crosscloudci/crosscloudci#11]
Performance tests are not needed for each PR so to save resources the CI can listen for PRs  tagged or labeled - `benchmark` or `release` - the only difference is that for `benchmark` it will compare with a previous commit and `release` will compare with a previous release. 

Here is how I imagine an e2e performance test could look like.

Kubernetes cluster with 9 physical machine(9 is not mandatory, just an example)
   * prometheus v1... - runs on an single node (affinity node1)
   * prometheus v2... - runs on another single node (affinity node2)
   * [fake-webserver](https://github.com/prometheus/prombench/tree/master/apps/fake-webserver) that  will be scraped - runs on 6 nodes (affinity node 3,4,5,6,7,8)  (400-500 replicas)
   * [load-generator and data collector](https://github.com/prometheus/prombench/tree/master/apps/load-generator) that will send requests to get the scraped data from both prometheus server - runs on another single node (affinity node9)

It will be a long running job at least 48h
At the end the data collector will fail or pass the job based on certain metric anomalies collected from both tested servers.

@taylor do you think something like this might be possible?

**Comment by krasi-georgiev** [comment]
ping @taylor

**Comment by taylor** [comment]
Howdy @krasi-georgiev, 

It looks like this performance test and its requirements are outside of CNCF's goals for the [CNCF CI Dashboard](https://cncf.ci) and the Cross-Cloud Ci project. This would be the case for any performance test.

The Cross-Cloud CI e2e tests needed for the [CNCF CI Dashboard](https://cncf.ci) are functional tests providing assurance of expected behavior for end-users.  Specifically, the tests should:

- help ensure interoperability between CNCF projects (eg. Prometheus being used by CoreDNS)
- validate functionality of a project running on Kubernetes across multiple cloud providers (optionally testing cloud provider specific flags) 
- complete within 1-2 hours (or less)
- limit the resource requirements (eg. memory, cpu, individual containers)

Of course, performance is important for the end-users as well.  I suggest creating a Prometheus CI project/ticket in the [Prometheus issue tracker](github.com/prometheus/prometheus/issues/) with the goal of meeting these project specific requirements.  (That project could of course utilize any of the software components from Cross-Cloud CI that fits those goals).

**Comment by krasi-georgiev** [comment]
@taylor thanks for the additional info.
Would you mind if we have a quick chat as I have some follow up questions.
I am krasi on #prometheus-dev or let me know where I can ping you.

**Comment by taylor** [comment]
@krasi-georgiev, sure.  I pinged you on IRC.  Shoot me a message when you get a chance.

**Comment by krasi-georgiev** [comment]
I didn't get the ping. Can you try again.

**Comment by dankohn** [comment]
@krasi-georgiev CNCF would be happy to provide server resources for Prometheus performance testing. Please open a request at https://github.com/cncf/cluster and we'll get you set up.

**Comment by krasi-georgiev** [comment]
@dankohn thanks, I think this has already been done thanks to @brancz .
We are now exploring the option how to automate the CI and benchmarking.
I am hoping that we can reuse some of the CNCF CI work and build what we need on top, that is why I wanted to have a quick chat with @taylor

**Comment by taylor** [comment]
@krasi-georgiev, I sent another DM on freenode this morning.  Please send me an email => taylor@vulk.coop.
