### ISSUE TITLE
[ONAP] Set up a VPN connection from the cross-cloud ci environment to the ONAP-Rackspace environment

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#16]
Good morning, @obriensystems.

May we please have your assistance re: VPN connections?

Thanks again.

---

**Feature Name:** 

- Set up a VPN connection from the cross-cloud ci environment to the ONAP-Rackspace environment
- VPN to ONAP's Rackspace environment for app deployments

**Short Description:** 

- ONAP-SO software running on Cross-Cloud CI needs to communicate with ONAP software running at Rackspace
- The ONAP Rackspace environment is private with no public network access

**Questions for ONAP:**

1. Does ONAP have any existing integrations using VPN that Cross-cloud can use? (ex. Cisco VPN Client, OpenVPN, VPN container)
1. What VPN software is running in the RackSpace VPN environment, if any?

**Comment by obriensystems** [comment]
Hi, there is a development and integration lab provided by Intel running openstack behind a VPN - is this what you mean?
See the following template for access 

https://jira.onap.org/browse/OPENLABS-75

Rackspace is a public openstack service - we don't really use it anymore because it is not configured for DNSaaS via designate (for the DCAEGEN2 component that is not containerized yet).
Rackspace is out of the picture except if you want to use it as a public facing Keystone server or to bring up VNFs publicly.

Do you wish to only bring up the so pod? wouldn't you also need several other components like aai?
Maybe we should have a zoom call and I can go over ONAP high level and see what you require
let me know

You can also join our wed 1000EDT (GMT-5) OOM weekly meeting where we could go over your requirements and introduce you to the team.
/michael

**Comment by lixuna** [comment]
@obriensystems - a zoom call to go over the ONAP high level and Cross-cloud CI requirements would be great! 

Are you available this afternoon, Thursday Feb 22 at 5pm EST or anytime tomorrow morning, Fri, Feb 23?

**Comment by lixuna** [comment]
@obriensystems thank you for your advice and walk through of the ONAP SO robot and SO containers today. 

We will de-prioritize this ticket as no action will be required for the initial ONAP + CNCF CI integration.

**Comment by obriensystems** [comment]
CNCF team,
   Good meeting the other day. Here is the video you requested for your reference of the session.
http://s3.amazonaws.com/onap/cncf_20180223_oom_zoom_0.mp4
   Also some links to get you starting brining up all of OOM deployed ONAP.

Posted to
https://github.com/crosscloudci/crosscloudci/issues/16
and
https://lists.onap.org/pipermail/onap-discuss/2018-February/008010.html
for
https://onsna18.sched.com/speaker/ajoshipura 

OOM
https://wiki.onap.org/display/DW/ONAP+Operations+Manager+Project
https://wiki.onap.org/display/DW/OOM+User+Guide
https://wiki.onap.org/display/DW/OOM+Developer+Guide


root deployment page
https://wiki.onap.org/display/DW/ONAP+on+Kubernetes
Running the rancher RI
https://wiki.onap.org/display/DW/ONAP+on+Kubernetes+on+Rancher
on multiple cloud system VM’s
https://wiki.onap.org/display/DW/ONAP+on+Kubernetes+on+Amazon+EC2
https://wiki.onap.org/display/DW/ONAP+on+Kubernetes+on+Microsoft+Azure

Mikes’ changes for SO (new config) and the older MSO – just went into master
https://gerrit.onap.org/r/#/q/status:merged+oom+standardized-configuration
